[package]
name = "wasmtest"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rod = { path = "../"}
pollster = "0.2.4"